from pymongo import MongoClient
client = MongoClient("mongodb://mfrt:YfkCgmLy4CtkIycY9HrCNueXrB6gEFJEyWHt8mUTewrGCymuYp2kPQzE8XclUW4VupkhYCdosOCCACDbnH27Zw==@mfrt.mongo.cosmos.azure.com:10255/?ssl=true&retrywrites=false&replicaSet=globaldb&maxIdleTimeMS=120000&appName=@mfrt@")
db = client["remedies"]
collection = db["collection1"]


ref={0: 'Apple___Apple_scab',
      1: 'Apple___Black_rot',
      2: 'Apple___Cedar_apple_rust',
      3: 'Apple___healthy',
      #4: 'Blueberry___healthy',
      4: 'Cherry_(including_sour)___Powdery_mildew',
      5: 'Cherry_(including_sour)___healthy',
      6: 'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot',
      7: 'Corn_(maize)___Common_rust_',
      8: 'Corn_(maize)___Northern_Leaf_Blight',
      9: 'Corn_(maize)___healthy',
      10: 'Grape___Black_rot',
      11: 'Grape___Esca_(Black_Measles)',
      12: 'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)',
      13: 'Grape___healthy',
      #15: 'Orange___Haunglongbing_(Citrus_greening)',
      14: 'Peach___Bacterial_spot',
      15: 'Peach___healthy',
      16: 'Pepper,_bell___Bacterial_spot',
      17: 'Pepper,_bell___healthy',
      18: 'Potato___Early_blight',
      19: 'Potato___Late_blight',
      20: 'Potato___healthy',
      #23: 'Raspberry___healthy',
      #24: 'Soybean___healthy',
      #25: 'Squash___Powdery_mildew',
      21: 'Strawberry___Leaf_scorch',
      22: 'Strawberry___healthy',
      23: 'Tomato___Bacterial_spot',
      24: 'Tomato___Early_blight',
      25: 'Tomato___Late_blight',
      26: 'Tomato___Leaf_Mold',
      27: 'Tomato___Septoria_leaf_spot',
      28: 'Tomato___Spider_mites Two-spotted_spider_mite',
      29: 'Tomato___Target_Spot',
      30: 'Tomato___Tomato_Yellow_Leaf_Curl_Virus',
      31: 'Tomato___Tomato_mosaic_virus',
      32: 'Tomato___healthy'}            
     
Apple___Apple_scab={'r0':"Apple scab is a fungal disease that affects apple trees, causing leaf spots, premature leaf drop, and fruit scabs. Here are some remedies for apple scab:",'r1':"Proper sanitation - Remove fallen leaves and infected fruit and dispose of them properly.",'r2':"Fungicide sprays - Apply fungicide sprays starting from early spring, and follow the instructions on the label.",'r3':"Cultural controls - Choose apple varieties that are resistant to apple scab and maintain proper air circulation by pruning the trees.",'r4':"Avoid overhead irrigation - Water the trees at the base of the trunk to avoid moistening the leaves.",'r5':"Improve soil health - Provide proper fertilization and maintain healthy soil conditions to promote the growth of strong and resistant trees.",'r6':"It's important to follow a regular spray schedule and practice good cultural practices to prevent apple scab."}
Apple___Black_rot={'r0':" Apple Black rot is a fungal disease that affects apple trees, causing fruit to rot and leaves to yellow and fall off. Here are some remedies for black rot:",'r1':"Crop rotation- Planting apple trees in fields that have not grown susceptible crops such as apples or crabapples in the previous 3-4 years can reduce the severity of the disease",'r2':"Pruning: Removing infected wood from apple trees and destroying it can help prevent the spread of the disease.",'r3':"Sanitation: Cleaning up fallen leaves, fruit, and other debris from the base of apple trees can reduce the amount of black rot spores that survive on the ground.",'r4':"Chemical control: Applying fungicides such as captan, mancozeb, or boscalid can help control black rot. These fungicides are most effective when applied before the onset of symptoms and should be reapplied at regular intervals throughout the growing season.",'r5':"Resistant cultivars: Planting apple cultivars that have shown resistance to black rot can also help reduce the severity of the disease.",'r6':"It is important to note that a combination of these remedies may be necessary for effective control of black rot disease."}
Apple___Cedar_apple_rust={'r0':"Cedar Apple Rust is a fungal disease that affects apple trees and is caused by the fungus Gymnosporangium juniperi-virginianae. Here are some remedies for cedar apple rust:",'r1':"Fungicide sprays: Applying fungicide sprays, such as triadimefon or myclobutanil, can help prevent and control the spread of the disease.",'r2':"Crop rotation: Planting apple trees in a different location every year can help reduce the amount of rust spores in the soil and reduce the risk of infection.",'r3':"Pruning and removing infected leaves: Regularly pruning and removing infected leaves from apple trees can reduce the spread of the disease and improve tree health.",'r4':"Maintaining a healthy tree: Keeping your apple trees healthy by providing adequate water, nutrients, and sunlight will improve their resistance to disease.",'r5':"Removing cedar trees: If possible, removing cedar trees in the vicinity of apple trees can greatly reduce the risk of infection.",'r6':"It's important to monitor your apple trees regularly and take prompt action to prevent and control Apple Cedar Apple Rust to protect their health and productivity."}
Apple___healthy={'r0':"It's healthy.Take care of it in the same way."}
Blueberry___healthy={'r0':"It's healthy.Take care of it in the same way."}
Cherry_including_sour_Powdery_mildew={'r0':"Cherry Powdery mildew is a fungal disease that affects cherries, causing a white powdery growth on the leaves, fruit, and stems. Here are some remedies for powdery mildew:",'r1':"There are several home remedies for cherry powdery mildew:",'r2':"Baking soda solution: Mix 1 tablespoon of baking soda and 1 tablespoon of horticultural oil in 1 gallon of water. Spray the solution on the infected leaves and branches.",'r3':"Neem oil: Mix 2.5 mL of neem oil in 1 liter of water and spray the solution on the infected parts of the plant.",'r4':"Garlic spray: Blend 3 cloves of garlic with 1 liter of water, strain and spray on the infected area.",'r5':"Potassium bicarbonate: Mix 1 teaspoon of potassium bicarbonate with 1 liter of water and spray on the infected area.",'r6':"It's important to regularly monitor your cherry tree for signs of powdery mildew and to apply these remedies at the first sign of infection. Additionally, avoid overcrowding plants and provide proper air circulation to reduce the likelihood of infection."}
Cherry_including_sour___healthy={'r0':"It's healthy.Take care of it in the same way."}
Corn_maize_Cercospora_leaf_spot_Gray_leaf_spot={'r0':"Maize Cercospora leaf spot and gray leaf spot are fungal diseases that affect corn plants. Here are some remedies for Cercospora leaf spot and gray leaf spot:",'r1':"Crop rotation: Planting corn in a different location every year can reduce the amount of fungal spores in the soil and reduce the risk of infection.",'r2':"Fungicide sprays: Applying fungicide sprays, such as chlorothalonil or azoxystrobin, can help prevent and control the spread of the disease.",'r3':"Sanitation: Regularly removing infected leaves and debris from the field can help reduce the spread of the disease.",'r4':"Resistant varieties: Planting corn varieties that are resistant to Cercospora leaf spot and Gray leaf spot can help reduce the risk of infection.",'r5':"Proper irrigation: Providing adequate water to the plants without allowing the leaves to stay wet for extended periods of time can help reduce the risk of infection.",'r6':"It's important to monitor your corn crops regularly and take prompt action to prevent and control Cercospora leaf spot and Gray leaf spot to protect their health and productivity."}
Corn_maize___Common_rust={'r0':"Maize Common rust is a fungal disease that affects corn plants. Here are some remedies for common rust:",'r1':"Crop rotation: Avoid planting corn in the same field year after year, as the fungal spores from the previous crop can survive in the soil and infect the new crop.",'r2':"Use resistant varieties: Plant corn varieties that have resistance to common rust.",'r3':"Fungicide application: Apply fungicides at the appropriate growth stage of the crop, as per the recommendation of a plant pathologist.",'r4':"Proper plant nutrition: Ensure that the plants receive adequate nutrients, especially potassium, which helps the plant to develop a thicker cuticle, making it less susceptible to fungal diseases.",'r5':"Sanitation: Remove and destroy infected leaves and debris to prevent the buildup and spread of the disease.",'r6':"Irrigation management: Proper irrigation management, such as avoiding overhead irrigation, can reduce the spread of fungal spores and increase the health of the plants.",'r7':"It's important to note that these remedies may not work in every situation, and a combination of these strategies may be necessary for effective disease management."}
Corn_maize___Northern_Leaf_Blight={'r0':"Maize Northern leaf blight is a fungal disease that affects corn plants, causing lesions on the leaves and reducing yield. Here are some remedies that can help control or prevent the disease:",'r1':"Crop rotation: Avoid planting corn in the same field for several years in a row. Instead, rotate with other crops that are not in the grass family.",'r2':"Resistant varieties: Planting corn varieties that have resistance to Northern Leaf Blight can reduce the impact of the disease.",'r3':"Fungicide application: Using fungicides specifically formulated to control Northern Leaf Blight can help prevent the spread of the disease. It's best to apply fungicides preventively, before the symptoms of the disease appear.",'r4':"Proper irrigation: Overhead irrigation can contribute to the spread of Northern Leaf Blight by providing an environment that is favorable for the fungus to grow. Drip irrigation or watering at the base of the plant can help reduce the spread of the disease.",'r5':"Sanitation: Remove and destroy infected plant debris from the previous season to reduce the number of spores and spores that can start new infections in the following season.",'r6':"It's important to implement a combination of these measures to effectively manage Northern Leaf Blight in corn crops."}
Corn_maize___healthy={'r0':"It's healthy.Take care of it in the same way."}
Grape___Black_rot={'r0':"Grape Black rot is a common disease that affects grapes and can cause significant damage to the fruit and vine. To control and prevent black rot, there are several cultural practices that can be implemented:",'r1':"Sanitation: Maintaining a clean vineyard is essential for reducing the spread of black rot. Remove and dispose of all infected fruit and leaves to prevent the spread of the disease.",'r2':"Crop rotation: Avoid planting grapes in the same location year after year, as this can lead to a buildup of disease spores in the soil.",'r3':"Pruning: Proper pruning can help to promote good air circulation in the vineyard, which can reduce the spread of black rot.",'r4':"Fungicide sprays: Spraying fungicides at regular intervals during the growing season can help to control the spread of black rot. Be sure to follow the instructions on the fungicide label carefully.",'r5':"Resistant varieties: Consider planting grape varieties that are known to be resistant to black rot.",'r6':"In addition to these cultural practices, it's important to monitor the vineyard regularly and take action as soon as symptoms of black rot are noticed. Early detection and treatment can help to reduce the severity of the disease and minimize crop losses."}
Grape___Esca_Black_Measles={'r0':"Grape Black Measles, also known as Esca is a fungal disease that affects grapevines. The following are some remedies that can help control and prevent the spread of the disease:",'r1':"Crop rotation: Avoid planting grapevines in the same location for several years in a row. This helps reduce the buildup of the fungal pathogen in the soil.",'r3':"Pruning and sanitization: Regularly prune infected parts of the vine and destroy them to reduce the spread of the disease. Sanitize your pruning tools between each cut to avoid spreading the fungus.",'r3':"Fungicides: Application of fungicides like Bordeaux mixture or copper-based fungicides can help control the spread of the disease.",'r4':"Proper nutrition: Maintaining the health of the grapevine by providing proper nutrition can help reduce its susceptibility to the disease.",'r5':"Good vineyard management practices: Implementing good vineyard management practices, such as proper irrigation and avoiding overcrowding, can help reduce the spread of the disease.",'r6':"It's important to note that controlling Grape Black Measles can be challenging and may require a combination of these remedies. It's also a good idea to consult with a local agricultural extension office or a professional viticulturist for specific recommendations for your area."}
Grape___Leaf_blight_Isariopsis_Leaf_Spot={'r0':"Grape Leaf blight, also known as Isariopsis leaf spot is a fungal disease that affects the leaves of grape vines. To control and prevent leaf blight, there are several cultural practices that can be implemented:",'r1':"Sanitation: Maintaining a clean vineyard is essential for reducing the spread of leaf blight. Remove and dispose of all infected leaves to prevent the spread of the disease.",'r2':"Crop rotation: Avoid planting grapes in the same location year after year, as this can lead to a buildup of disease fragments in the soil.",'r3':"Pruning: Proper pruning can help to promote good air circulation in the vineyard, which can reduce the spread of leaf blight.",'r4':"Fungicide sprays: Spraying fungicides at regular intervals during the growing season can help to control the spread of leaf blight. Be sure to follow the instructions on the fungicide label carefully.",'r5':"Resistant varieties: Consider planting grape varieties that are known to be resistant to leaf blight.",'r6':"In addition to these cultural practices, it's important to monitor the vineyard regularly and take action as soon as symptoms of leaf blight are noticed. Early detection and treatment can help to reduce the severity of the disease and minimize crop losses."}
Grape___healthy={'r0':"It's healthy.Take care of it in the same way."}
Orange___Haunglongbing_Citrus_greening={'r0':"Haunglongbing, also known as citrus greening, is a serious disease that affects citrus trees, including oranges. The disease is caused by a bacterium and is spread by a tiny insect called the Asian citrus psyllid. To control and prevent citrus greening, there are several cultural practices that can be implemented:",'r1':"Sanitation: Maintaining a clean orchard is essential for reducing the spread of citrus greening. Remove and dispose of all infected trees and any fallen leaves or fruit to prevent the spread of the disease.",'r2':"Pesticide application: Spraying insecticides to control the Asian citrus psyllid is an important step in preventing the spread of citrus greening. Be sure to follow the instructions on the pesticide label carefully.",'r3':"Monitoring: Regularly inspect the orchard for signs of citrus greening and take action as soon as symptoms are noticed. Early detection is key to controlling the disease.",'r4':"Choosing resistant varieties: Consider planting citrus varieties that are known to be resistant to citrus greening.",'r5':"Quarantine measures: Implement quarantine measures to prevent the spread of the disease from infected areas to healthy areas. This may include restrictions on the movement of citrus plants and plant material.",'r6':"It is important to note that there is no cure for citrus greening once a tree is infected, and infected trees will eventually die. However, implementing these cultural practices can help to slow the spread of the disease and reduce its impact on citrus orchards."}
Peach___Bacterial_spot={'r0':"Peach Bacterial spot is a common disease that affects peaches and can cause significant damage to the fruit and leaves. To control and prevent bacterial spot, there are several cultural practices that can be implemented:",'r1':"Sanitation: Maintaining a clean orchard is essential for reducing the spread of bacterial spot. Remove and dispose of all infected leaves and fruit to prevent the spread of the disease.",'r2':"Crop rotation: Avoid planting peaches in the same location year after year, as this can lead to a buildup of disease fragments in the soil.",'r3':"Pruning: Proper pruning can help to promote good air circulation in the orchard, which can reduce the spread of bacterial spot.",'r4':"Copper sprays: Spraying copper-based fungicides at regular intervals during the growing season can help to control the spread of bacterial spot. Be sure to follow the instructions on the fungicide label carefully.",'r5':"Resistant varieties: Consider planting peach varieties that are known to be resistant to bacterial spot.",'r6':"In addition to these cultural practices, it's important to monitor the orchard regularly and take action as soon as symptoms of bacterial spot are noticed. Early detection and treatment can help to reduce the severity of the disease and minimize crop losses."}
Peach___healthy={'r0':"It's healthy.Take care of it in the same way."}
Pepper_bell___Bacterial_spot={'r0':"Pepper Bell Bacterial spot is a common disease that affects bell peppers and can cause significant damage to the fruit and leaves. To control and prevent bacterial spot, there are several cultural practices that can be implemented:",'r1':"Sanitation: Maintaining a clean garden or field is essential for reducing the spread of bacterial spot. Remove and dispose of all infected leaves and fruit to prevent the spread of the disease.",'r2':"Crop rotation: Avoid planting peppers in the same location year after year, as this can lead to a buildup of disease fragments in the soil.",'r3':"Proper irrigation: Avoid overhead watering, as this can spread the disease and increase the severity of infection. Instead, use drip irrigation or water the plants at the base of the plant.",'r4':"Copper sprays: Spraying copper-based fungicides at regular intervals during the growing season can help to control the spread of bacterial spot. Be sure to follow the instructions on the fungicide label carefully.",'r5':"Resistant varieties: Consider planting bell pepper varieties that are known to be resistant to bacterial spot.",'r6':"In addition to these cultural practices, it's important to monitor the garden or field regularly and take action as soon as symptoms of bacterial spot are noticed. Early detection and treatment can help to reduce the severity of the disease and minimize crop losses."}
Pepper_bell___healthy={'r0':"It's healthy.Take care of it in the same way."}
Potato___Early_blight={'r0':"Potato Early blight is a common disease that affects potatoes and can cause significant damage to the leaves, stems, and tubers of the plant. To control and prevent early blight, there are several cultural practices that can be implemented:",'r1':"Sanitation: Maintaining a clean garden or field is essential for reducing the spread of early blight. Remove and dispose of all infected leaves and plant debris to prevent the spread of the disease.",'r2':"Crop rotation: Avoid planting potatoes in the same location year after year, as this can lead to a buildup of disease fragments in the soil.",'r3':"Proper irrigation: Avoid overhead watering, as this can spread the disease and increase the severity of infection. Instead, use drip irrigation or water the plants at the base of the plant.",'r4':"Fungicide sprays: Spraying fungicides at regular intervals during the growing season can help to control the spread of early blight. Be sure to follow the instructions on the fungicide label carefully.",'r5':"Resistant varieties: Consider planting potato varieties that are known to be resistant to early blight.",'r6':"In addition to these cultural practices, it's important to monitor the garden or field regularly and take action as soon as symptoms of early blight are noticed. Early detection and treatment can help to reduce the severity of the disease and minimize crop losses."}
Potato___Late_blight={'r0':"Potato Late blight is a serious and potentially devastating disease that affects potatoes and tomatoes. To control and prevent late blight, there are several cultural practices that can be implemented:",'r1':"Sanitation: Maintaining a clean garden or field is essential for reducing the spread of late blight. Remove and dispose of all infected leaves and plant debris to prevent the spread of the disease.",'r2':"Crop rotation: Avoid planting potatoes and tomatoes in the same location year after year, as this can lead to a buildup of disease fragments in the soil.",'r3':"Proper irrigation: Avoid overhead watering, as this can spread the disease and increase the severity of infection. Instead, use drip irrigation or water the plants at the base of the plant.",'r4':"Fungicide sprays: Spraying fungicides at regular intervals during the growing season can help to control the spread of late blight. Be sure to follow the instructions on the fungicide label carefully.",'r5':"Fungicide sprays: Spraying fungicides at regular intervals during the growing season can help to control the spread of late blight. Be sure to follow the instructions on the fungicide label carefully.",'r6':"In addition to these cultural practices, it's important to monitor the garden or field regularly and take action as soon as symptoms of late blight are noticed. Early detection and treatment can help to reduce the severity of the disease and minimize crop losses."}
Potato___healthy={'r0':"It's healthy.Take care of it in the same way."}
Raspberry___healthy={'r0':"It's healthy.Take care of it in same way"}
Soybean___healthy={'r0':"It's healthy.Take care of it in same way"}
Squash___Powdery_mildew={'r0':"Powdery mildew is a common fungal disease that affects a variety of plants, including squash. To control and prevent powdery mildew, there are several cultural practices that can be implemented:",'r1':"Sanitation: Maintaining a clean garden or field is essential for reducing the spread of powdery mildew. Remove and dispose of all infected leaves and plant debris to prevent the spread of the disease.",'r2':"Proper spacing: Allow enough space between plants to promote good air circulation and reduce the humidity levels in the garden or field.",'r3':"Proper irrigation: Avoid overhead watering, as this can spread the disease and increase the severity of infection. Instead, use drip irrigation or water the plants at the base of the plant.",'r4':"Fungicide sprays: Spraying fungicides at regular intervals during the growing season can help to control the spread of powdery mildew. Be sure to follow the instructions on the fungicide label carefully.",'r5':"Resistant varieties: Consider planting squash varieties that are known to be resistant to powdery mildew.",'r6':"In addition to these cultural practices, it's important to monitor the garden or field regularly and take action as soon as symptoms of powdery mildew are noticed. Early detection and treatment can help to reduce the severity of the disease and minimize crop losses."}
Strawberry___Leaf_scorch={'r0':"Strawberry leaf scorch is a condition that can cause yellowing, wilting, and browning of the leaves of strawberry plants. Some possible remedies for strawberry leaf scorch include:",'r1':"Water Management: Ensure that your strawberry plants are receiving consistent, but not excessive, water. This can help prevent the leaf scorch caused by dry soil.",'r2':"Mulching: A layer of mulch around the base of the plant can help to retain moisture in the soil and regulate the temperature of the soil, reducing the likelihood of leaf scorch.",'r3':"Pruning: Removing infected leaves can help to reduce the spread of the leaf scorch and promote healthy growth of the plant.",'r4':"Fertilizing: Using a balanced fertilizer can help to promote healthy growth and encourage the plant to recover from the leaf scorch.",'r5':"Avoiding Stress: Protect the plant from stress caused by extreme temperatures, drought, and other environmental conditions.",'r6':"It's important to keep in mind that while these remedies may help reduce the severity of the leaf scorch, they may not completely eliminate the problem. If the leaf scorch is caused by a fungal or bacterial infection, a fungicide or bactericide may be necessary to fully resolve the issue."}
Strawberry___healthy={'r0':"It's healthy.Take care of it in the same way."}
Tomato___Bacterial_spot={'r0':"Tomato bacterial spot is a common problem in tomato plants that is caused by the bacterium Xanthomonas campestris. Here are some remedies for tomato bacterial spot",'r1':"Crop rotation: Planting tomatoes in a different location each year can help reduce the buildup of bacteria in the soil.",'r2':"Sanitation: Clean up any plant debris in and around the tomato plants to reduce the number of bacteria present.",'r3':"Resistant varieties: Choose tomato varieties that are resistant to bacterial spot.",'r4':"Avoid overhead watering: Watering the tomato plants from below, such as through drip irrigation, can help reduce the spread of the bacteria.",'r5':"Copper sprays: Copper-based fungicides can be used as a preventative measure to help reduce the severity of bacterial spot.",'r6':"Remove infected leaves: Regularly removing any infected leaves and disposing of them far from the tomato plants can help reduce the spread of the bacteria.",'r7':"It's important to follow good cultural practices, such as providing adequate spacing between plants, avoiding overcrowding, and providing adequate sunlight, water, and nutrients to the plants, as this can also help reduce the severity of bacterial spot. Additionally, it is recommended to avoid overhead watering and to take measures to reduce the spread of bacteria, such as using clean tools and avoiding working with the plants when they are wet."}
Tomato___Early_blight={'r0':"Tomato Early blight is a fungal disease that affects tomato plants, causing leaf yellowing and defoliation, and can also affect the fruit. Here are some remedies for early blight in tomatoes:",'r1':"Crop rotation: Planting tomatoes in a different location each year can help reduce the buildup of the fungus in the soil.",'r2':"Sanitation: Clean up any plant debris in and around the tomato plants to reduce the number of spores of the fungus present.",'r3':"Resistant varieties: Choose tomato varieties that are resistant to early blight.",'r4':"Proper watering: Watering the tomato plants at the base of the plant and avoiding overhead watering can help reduce the spread of the fungus.",'r5':"Fungicides: Fungicides containing chlorothalonil, mancozeb, or copper can be used as a preventative measure or to control early blight.",'r6':"Stake or cage the plants: Properly staking or caging the tomato plants can increase air flow and reduce humidity, which can help prevent the development of early blight.",'r7':"Remove infected leaves: Regularly removing any infected leaves and disposing of them far from the tomato plants can help reduce the spread of the fungus.",'r8':"It's important to follow good cultural practices, such as providing adequate spacing between plants, avoiding overcrowding, and providing adequate sunlight, water, and nutrients to the plants, as this can also help reduce the severity of early blight. Additionally, it is recommended to avoid overhead watering and to take measures to reduce the spread of the fungus, such as using clean tools and avoiding working with the plants when they are wet."}
Tomato___Late_blight={'r0':"Tomato Late blight is a fungal disease that affects tomato and potato plants, causing rapid wilting, yellowing, and blackening of the leaves and stems. Here are some remedies for late blight in tomatoes:",'r1':"Crop rotation: Planting tomatoes in a different location each year can help reduce the buildup of the fungus in the soil.",'r2':"Resistant varieties: Choose tomato varieties that are resistant to late blight.",'r3':"Proper watering: Watering the tomato plants at the base of the plant and avoiding overhead watering can help reduce the spread of the fungus.",'r4':"Fungicides: Fungicides containing mefenoxam or mancozeb can be used as a preventative measure or to control late blight.",'r5':"Stake or cage the plants: Properly staking or caging the tomato plants can increase air flow and reduce humidity, which can help prevent the development of late blight.",'r6':"Remove infected plants: Remove and destroy any infected plants to prevent the spread of the fungus.",'r7':"Sanitation: Clean up any plant debris in and around the tomato plants to reduce the number of fragments of the fungus present.",'r8':"It's important to follow good cultural practices, such as providing adequate spacing between plants, avoiding overcrowding, and providing adequate sunlight, water, and nutrients to the plants, as this can also help reduce the severity of late blight. Additionally, it is recommended to avoid overhead watering and to take measures to reduce the spread of the fungus, such as using clean tools and avoiding working with the plants when they are wet.",'r9':"Note: Late blight can be a serious disease and it is important to take preventive measures to protect your tomato plants from infection. If you live in an area with a high risk of late blight, it may be best to avoid growing susceptible tomato and potato varieties altogether."}
Tomato___Leaf_Mold={'r0':"Tomato leaf mold is a fungal disease that causes yellow spots on the leaves, which can eventually turn brown and become covered in a fuzzy, gray mold. Here are some remedies for tomato leaf mold:",'r1':"Crop rotation: Planting tomatoes in a different location each year can help reduce the buildup of the fungus in the soil.",'r2':"Proper spacing: Providing adequate spacing between plants can increase air flow and reduce humidity, which can help prevent the development of leaf mold.",'r3':"Resistant varieties: Choose tomato varieties that are resistant to leaf mold.",'r4':"Proper watering: Watering the tomato plants at the base of the plant and avoiding overhead watering can help reduce the spread of the fungus.",'r5':"Fungicides: Fungicides containing chlorothalonil or mancozeb can be used as a preventative measure or to control leaf mold.",'r6':"Stake or cage the plants: Properly staking or caging the tomato plants can increase air flow and reduce humidity, which can help prevent the development of leaf mold.",'r7':"Remove infected leaves: Regularly removing any infected leaves and disposing of them far from the tomato plants can help reduce the spread of the fungus.",'r8':"It's important to follow good cultural practices, such as providing adequate sunlight, water, and nutrients to the plants, as this can also help reduce the severity of leaf mold. Additionally, it is recommended to avoid overhead watering and to take measures to reduce the spread of the fungus, such as using clean tools and avoiding working with the plants when they are wet."}
Tomato___Septoria_leaf_spot={'r0':"Tomato Septoria leaf spot is a fungal disease that affects tomato plants, causing small, circular, brown or black spots on the leaves. Here are some remedies for septoria leaf spot in tomatoes:",'r1':"Crop rotation: Planting tomatoes in a different location each year can help reduce the buildup of the fungus in the soil.",'r2':"Sanitation: Clean up any plant debris in and around the tomato plants to reduce the number of fragments of the fungus present.",'r3':"Resistant varieties: Choose tomato varieties that are resistant to septoria leaf spot.",'r4':"Proper watering: Watering the tomato plants at the base of the plant and avoiding overhead watering can help reduce the spread of the fungus.",'r5':"Fungicides: Fungicides containing chlorothalonil, mancozeb, or copper can be used as a preventative measure or to control septoria leaf spot.",'r6':"Stake or cage the plants: Properly staking or caging the tomato plants can increase air flow and reduce humidity, which can help prevent the development of septoria leaf spot.",'r7':"Remove infected leaves: Regularly removing any infected leaves and disposing of them far from the tomato plants can help reduce the spread of the fungus.",'r8':"It's important to follow good cultural practices, such as providing adequate spacing between plants, avoiding overcrowding, and providing adequate sunlight, water, and nutrients to the plants, as this can also help reduce the severity of septoria leaf spot. Additionally, it is recommended to avoid overhead watering and to take measures to reduce the spread of the fungus, such as using clean tools and avoiding working with the plants when they are wet."}
Tomato___Spider_mites_Twos_potted_spider_mite={'r0':"Tomato Spider mites are tiny, spider-like pests that feed on the undersides of tomato leaves, causing yellow stippling and premature leaf drop. Here are some remedies for spider mites in tomatoes:",'r1':"Water: Regularly watering the plants and increasing humidity can help reduce spider mite populations.",'r2':"Predatory insects: Encouraging the presence of predatory insects, such as ladybugs and lacewings, can help control spider mite populations.",'r3':"Neem oil: Neem oil, a natural insecticide derived from the neem tree, can be effective in controlling spider mites.",'r4':"Hosing off plants: Regularly hosing off the plants with a strong stream of water can physically remove spider mites.",'r5':"Chemical insecticides: Chemical insecticides, such as insecticidal soap or horticultural oil, can be effective in controlling spider mites. However, it's important to follow the label instructions carefully and avoid using these products during hot weather, as they can damage the foliage.",'r6':"Companion planting: Planting herbs and companion plants, such as marigolds, can help repel spider mites.",'r7':"It's important to take preventative measures, such as avoiding overcrowding and providing adequate sunlight and nutrients, to keep tomato plants healthy and less attractive to spider mites. Additionally, it's important to monitor your plants regularly for signs of spider mites and take action at the first sign of infestation to prevent a larger problem from developing."}
Tomato___Target_Spot={'r0':"Tomato Target spot is a fungal disease that affects tomato plants, causing circular, dark brown to black spots on the leaves, stems, and fruit. Here are some remedies for target spot in tomatoes:",'r1':"Crop rotation: Planting tomatoes in a different location each year can help reduce the buildup of the fungus in the soil.",'r2':"Resistant varieties: Choose tomato varieties that are resistant to target spot.",'r3':"Proper watering: Watering the tomato plants at the base of the plant and avoiding overhead watering can help reduce the spread of the fungus.",'r4':"Fungicides: Fungicides containing chlorothalonil, mancozeb, or copper can be used as a preventative measure or to control target spot.",'r5':"Stake or cage the plants: Properly staking or caging the tomato plants can increase air flow and reduce humidity, which can help prevent the development of target spot.",'r6':"Remove infected leaves: Regularly removing any infected leaves and disposing of them far from the tomato plants can help reduce the spread of the fungus.",'r7':"It's important to follow good cultural practices, such as providing adequate spacing between plants, avoiding overcrowding, and providing adequate sunlight, water, and nutrients to the plants, as this can also help reduce the severity of target spot. Additionally, it's important to avoid overhead watering and to take measures to reduce the spread of the fungus, such as using clean tools and avoiding working with the plants when they are wet."}
Tomato___Tomato_Yellow_Leaf_Curl_Virus={'r0':"Tomato yellow leaf curl virus (TYLCV) is a serious viral disease that affects tomato plants, causing yellowing, curling, and stunting of the leaves, as well as reduced yields and quality of the fruit. Unfortunately, there is no cure for TYLCV, and infected plants should be removed and destroyed to prevent the spread of the virus. Here are some remedies for TYLCV in tomatoes:",'r1':"Use resistant varieties: Some tomato varieties have been developed that are resistant to TYLCV, so it's a good idea to choose these varieties if you are planting in an area with a history of TYLCV.",'r2':"Prevent the spread of the virus: The whitefly, a tiny insect, is the primary vector of TYLCV, so it's important to take measures to reduce whitefly populations, such as using yellow sticky traps, removing weeds and volunteer tomatoes that can serve as alternate hosts, and using insecticidal soap or other insecticides to control whiteflies.",'r3':"Avoid spreading the virus: If you are working with infected plants, be sure to disinfect your tools and wash your hands and clothing before working with healthy plants to avoid spreading the virus.",'r4':"Remove infected plants: As soon as you suspect that a plant may be infected with TYLCV, remove it from your garden and destroy it.",'r5':"Practice good cultural practices: Providing adequate sunlight, water, and nutrients, and avoiding overcrowding, can help keep your tomato plants healthy and less susceptible to TYLCV and other diseases.",'r6':"It's important to monitor your tomato plants regularly for signs of TYLCV, such as yellowing, curling, and stunting of the leaves, and to take action as soon as you suspect that a plant may be infected. The earlier you detect and remove infected plants, the less chance there is for the virus to spread to healthy plants."}
Tomato___Tomato_mosaic_virus={'r0':"Tomato mosaic virus (ToMV) is a viral disease that affects tomato plants, causing mottling, yellowing, stunting, and reduced yields. There is no cure for ToMV, and infected plants should be removed and destroyed to prevent the spread of the virus. Here are some remedies for ToMV in tomatoes:",'r1':"Use resistant varieties: Some tomato varieties have been developed that are resistant to ToMV, so it's a good idea to choose these varieties if you are planting in an area with a history of ToMV.",'r2':"Prevent the spread of the virus: ToMV is transmitted by several types of insects, as well as through contaminated seed and tools, so it's important to take measures to reduce the spread of the virus, such as using insecticides to control insect populations, planting only disease-free seed, and disinfecting tools between uses.",'r3':"Avoid spreading the virus: If you are working with infected plants, be sure to disinfect your tools and wash your hands and clothing before working with healthy plants to avoid spreading the virus.",'r4':"Remove infected plants: As soon as you suspect that a plant may be infected with ToMV, remove it from your garden and destroy it.",'r5':"Practice good cultural practices: Providing adequate sunlight, water, and nutrients, and avoiding overcrowding, can help keep your tomato plants healthy and less susceptible to ToMV and other diseases.",'r6':"It's important to monitor your tomato plants regularly for signs of ToMV, such as mottling, yellowing, stunting, and reduced yields, and to take action as soon as you suspect that a plant may be infected. The earlier you detect and remove infected plants, the less chance there is for the virus to spread to healthy plants."}
Tomato___healthy={'r0':"It's healthy.Take care of it in the same way."}



remedies={0:Apple___Apple_scab,1:Apple___Black_rot,2:Apple___Cedar_apple_rust,3:Apple___healthy,4:Cherry_including_sour_Powdery_mildew,5:Cherry_including_sour___healthy,6:Corn_maize_Cercospora_leaf_spot_Gray_leaf_spot,7:Corn_maize___Common_rust,8:Corn_maize___Northern_Leaf_Blight,9: Corn_maize___healthy,10:Grape___Black_rot,11:Grape___Esca_Black_Measles,12:Grape___Leaf_blight_Isariopsis_Leaf_Spot,13:Grape___healthy,14:Peach___Bacterial_spot,15:Peach___healthy,16:Pepper_bell___Bacterial_spot,17:Pepper_bell___healthy,18:Potato___Early_blight,19:Potato___Late_blight,20:Potato___healthy,21:Strawberry___Leaf_scorch,22:Strawberry___healthy,23:Tomato___Bacterial_spot,24:Tomato___Early_blight,25:Tomato___Late_blight,26:Tomato___Leaf_Mold,27:Tomato___Septoria_leaf_spot,28:Tomato___Spider_mites_Twos_potted_spider_mite,29:Tomato___Target_Spot,30:Tomato___Tomato_Yellow_Leaf_Curl_Virus,31:Tomato___Tomato_mosaic_virus,32:Tomato___healthy}

for disease in remedies:
    document={}
    document["_id"] =ref[disease]
    document["r"]=remedies[disease]    
    result = collection.insert_one(document)